### ISSUE TITLE
can't find pytorch=0.4.1=py36_py35_py27__9.0.176_7.1.2_2

### ISSUE THREAD

**Issue by 2019211753** [ASGuard-UCI/MSF-ADV#10]
Can I find another library to replace it? When I replace it with pytorch=0.41, I get an error:
Traceback (most recent call last):
  File "attack.py", line 2, in <module>
    import neural_renderer as nr
  File "/home/data3_2.5/yb/anaconda3/envs/msf-adv/lib/python3.6/site-packages/neural_renderer/__init__.py", line 3, in <module>
    from .load_obj import load_obj
  File "/home/data3_2.5/yb/anaconda3/envs/msf-adv/lib/python3.6/site-packages/neural_renderer/load_obj.py", line 8, in <module>
    import neural_renderer.cuda.load_textures as load_textures_cuda
ImportError: /home/data3_2.5/yb/anaconda3/envs/msf-adv/lib/python3.6/site-packages/neural_renderer/cuda/load_textures.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationESs

**Comment by hansoogithub** [comment]
im also facing the same issue with the same results

**Comment by xiaoxiaowu99** [comment]
> im also facing the same issue with the same results

If you need help, you can contact me to solve it.

**Comment by zahid414** [comment]
how did you solve this problem?

**Comment by QuteSaltyFish** [comment]
same issue here, any solutions?
