### ISSUE TITLE
undefined symbol: __cudaRegisterFatBinaryEnd

### ISSUE THREAD

**Issue by nowangry** [ASGuard-UCI/MSF-ADV#4]
When I run the example command:

`python attack.py -obj ./object/object.ply -obj_save ./object/obj_save -lidar ./data/lidar.bin -cam ./data/cam.png -cali ./data/cali.txt -e 0.2 -o pgd -it 1000 `
I got:
Traceback (most recent call last):
  File "attack.py", line 2, in <module>
    import neural_renderer as nr
  File "/home/jqwu/.conda/envs/msf-adv/lib/python3.6/site-packages/neural_renderer/__init__.py", line 3, in <module>
    from .load_obj import load_obj
  File "/home/jqwu/.conda/envs/msf-adv/lib/python3.6/site-packages/neural_renderer/load_obj.py", line 8, in <module>
    import neural_renderer.cuda.load_textures as load_textures_cuda
ImportError: /home/jqwu/.conda/envs/msf-adv/lib/python3.6/site-packages/neural_renderer/cuda/load_textures.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaRegisterFatBinaryEnd

I have already changed my CUDA path to use the version 9.0:
`export PATH=/usr/local/cuda-9.0/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64:$LD_LIBRARY_PATH`
My gcc version is 5.4.0:
`gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)`

Any suggestions? Thanks a lot !!

**Comment by Asimion-2** [comment]
Did you ever solve this issue? I am currently facing the same issue.

**Comment by hxlCHD** [comment]
I have faced this same issue and solved it.But I don't konw  whether this is right way.I just make it run.This is my way:
1. change the CUDA version and GCC version, just like what you have did
2. clone the source file of neural renderer from github
3. check the pytorch version. For me is 0.4.1, But the readme recommend 0.4.0, I konw from a blog which said that higher version has some syntax changes, high version use TORCH_CHECK instead of AT_CHECK. so I just edit all the cpp files in this folder:/yourWorkSpace/neural_renderer/neural_renderer/cuda, replace all the TORCH_CHECK to AT_CHECK. 
4. then compile the source code i have modified. `python setup.py install` I run this command in the msf-adv environment.
5. remove the neural-renderer-pytorch  which installed by conda. use this commend to uninstall `pip uninstall neural-renderer-pytorch=1.1.3`, I think you can edit the requirements.yml to avoid installing neural-renderer-pytorch from begin and then perform the previous step. 
I hope these will help you！

**Comment by chunhez** [comment]
> I have faced this same issue and solved it.But I don't konw whether this is right way.I just make it run.This is my way:
> 
> 1. change the CUDA version and GCC version, just like what you have did
> 2. clone the source file of neural renderer from github
> 3. check the pytorch version. For me is 0.4.1, But the readme recommend 0.4.0, I konw from a blog which said that higher version has some syntax changes, high version use TORCH_CHECK instead of AT_CHECK. so I just edit all the cpp files in this folder:/yourWorkSpace/neural_renderer/neural_renderer/cuda, replace all the TORCH_CHECK to AT_CHECK.
> 4. then compile the source code i have modified. `python setup.py install` I run this command in the msf-adv environment.
> 5. remove the neural-renderer-pytorch  which installed by conda. use this commend to uninstall `pip uninstall neural-renderer-pytorch=1.1.3`, I think you can edit the requirements.yml to avoid installing neural-renderer-pytorch from begin and then perform the previous step.
>    I hope these will help you！

@[hxlCHD](https://github.com/hxlCHD) Hi, I followed your instructions but when I tried to run command `python setup.py install`, it gave the error that 'TORCH_CHECK' was not declared in this scope. Could you specify what versions for GCC and CUDA you are using? I'm using GCC 5.4 and CUDA 9.0. I checked my pytorch is also 0.4.1.

Thanks!

**Comment by hxlCHD** [comment]
@chunhez 
Thanks for your reply!
I am using the GCC 5.4.0 and CUDA 9.0,too. but the neural_renderer also need G++ compiler (I'm sorry that I forgot to note that,haha!), the older version just like 5.3 seems not working correctly, so I change the G++ to 9.4.

**Comment by hxlCHD** [comment]
> > I have faced this same issue and solved it.But I don't konw whether this is right way.I just make it run.This is my way:
> > 
> > 1. change the CUDA version and GCC version, just like what you have did
> > 2. clone the source file of neural renderer from github
> > 3. check the pytorch version. For me is 0.4.1, But the readme recommend 0.4.0, I konw from a blog which said that higher version has some syntax changes, high version use TORCH_CHECK instead of AT_CHECK. so I just edit all the cpp files in this folder:/yourWorkSpace/neural_renderer/neural_renderer/cuda, replace all the TORCH_CHECK to AT_CHECK.
> > 4. then compile the source code i have modified. `python setup.py install` I run this command in the msf-adv environment.
> > 5. remove the neural-renderer-pytorch  which installed by conda. use this commend to uninstall `pip uninstall neural-renderer-pytorch=1.1.3`, I think you can edit the requirements.yml to avoid installing neural-renderer-pytorch from begin and then perform the previous step.
> >    I hope these will help you！
> 
> @[hxlCHD](https://github.com/hxlCHD) Hi, I followed your instructions but when I tried to run command `python setup.py install`, it gave the error that 'TORCH_CHECK' was not declared in this scope. Could you specify what versions for GCC and CUDA you are using? I'm using GCC 5.4 and CUDA 9.0. I checked my pytorch is also 0.4.1.
> 
> Thanks!
@chunhez 
Thanks for your reply!
I am using the GCC 5.4.0 and CUDA 9.0,too. but the neural_renderer also need G++ compiler (I'm sorry that I forgot to note that,haha!), the older version just like 5.3 seems not working correctly, so I change the G++ to 9.4.

**Comment by hxlCHD** [comment]
> > I have faced this same issue and solved it.But I don't konw whether this is right way.I just make it run.This is my way:
> > 
> > 1. change the CUDA version and GCC version, just like what you have did
> > 2. clone the source file of neural renderer from github
> > 3. check the pytorch version. For me is 0.4.1, But the readme recommend 0.4.0, I konw from a blog which said that higher version has some syntax changes, high version use TORCH_CHECK instead of AT_CHECK. so I just edit all the cpp files in this folder:/yourWorkSpace/neural_renderer/neural_renderer/cuda, replace all the TORCH_CHECK to AT_CHECK.
> > 4. then compile the source code i have modified. `python setup.py install` I run this command in the msf-adv environment.
> > 5. remove the neural-renderer-pytorch  which installed by conda. use this commend to uninstall `pip uninstall neural-renderer-pytorch=1.1.3`, I think you can edit the requirements.yml to avoid installing neural-renderer-pytorch from begin and then perform the previous step.
> >    I hope these will help you！
> 
> @[hxlCHD](https://github.com/hxlCHD) Hi, I followed your instructions but when I tried to run command `python setup.py install`, it gave the error that 'TORCH_CHECK' was not declared in this scope. Could you specify what versions for GCC and CUDA you are using? I'm using GCC 5.4 and CUDA 9.0. I checked my pytorch is also 0.4.1.
> 
> Thanks!

I think my previous comment have made a mistake. I checked my cpp files just now. I just replace all the TORCH_CHECK to AT_CHECK.

**Comment by chunhez** [comment]
> > > I have faced this same issue and solved it.But I don't konw whether this is right way.I just make it run.This is my way:
> > > 
> > > 1. change the CUDA version and GCC version, just like what you have did
> > > 2. clone the source file of neural renderer from github
> > > 3. check the pytorch version. For me is 0.4.1, But the readme recommend 0.4.0, I konw from a blog which said that higher version has some syntax changes, high version use TORCH_CHECK instead of AT_CHECK. so I just edit all the cpp files in this folder:/yourWorkSpace/neural_renderer/neural_renderer/cuda, replace all the TORCH_CHECK to AT_CHECK.
> > > 4. then compile the source code i have modified. `python setup.py install` I run this command in the msf-adv environment.
> > > 5. remove the neural-renderer-pytorch  which installed by conda. use this commend to uninstall `pip uninstall neural-renderer-pytorch=1.1.3`, I think you can edit the requirements.yml to avoid installing neural-renderer-pytorch from begin and then perform the previous step.
> > >    I hope these will help you！
> > 
> > 
> > @[hxlCHD](https://github.com/hxlCHD) Hi, I followed your instructions but when I tried to run command `python setup.py install`, it gave the error that 'TORCH_CHECK' was not declared in this scope. Could you specify what versions for GCC and CUDA you are using? I'm using GCC 5.4 and CUDA 9.0. I checked my pytorch is also 0.4.1.
> > Thanks!
> > @chunhez
> > Thanks for your reply!
> > I am using the GCC 5.4.0 and CUDA 9.0,too. but the neural_renderer also need G++ compiler (I'm sorry that I forgot to note that,haha!), the older version just like 5.3 seems not working correctly, so I change the G++ to 9.4.

@hxlCHD Thanks for your reply! So you mean you have to use different versions for GCC and G++? You have GCC 5.4 and G++9.4?

**Comment by hxlCHD** [comment]
> > > > I have faced this same issue and solved it.But I don't konw whether this is right way.I just make it run.This is my way:
> > > > 
> > > > 1. change the CUDA version and GCC version, just like what you have did
> > > > 2. clone the source file of neural renderer from github
> > > > 3. check the pytorch version. For me is 0.4.1, But the readme recommend 0.4.0, I konw from a blog which said that higher version has some syntax changes, high version use TORCH_CHECK instead of AT_CHECK. so I just edit all the cpp files in this folder:/yourWorkSpace/neural_renderer/neural_renderer/cuda, replace all the TORCH_CHECK to AT_CHECK.
> > > > 4. then compile the source code i have modified. `python setup.py install` I run this command in the msf-adv environment.
> > > > 5. remove the neural-renderer-pytorch  which installed by conda. use this commend to uninstall `pip uninstall neural-renderer-pytorch=1.1.3`, I think you can edit the requirements.yml to avoid installing neural-renderer-pytorch from begin and then perform the previous step.
> > > >    I hope these will help you！
> > > 
> > > 
> > > @[hxlCHD](https://github.com/hxlCHD) Hi, I followed your instructions but when I tried to run command `python setup.py install`, it gave the error that 'TORCH_CHECK' was not declared in this scope. Could you specify what versions for GCC and CUDA you are using? I'm using GCC 5.4 and CUDA 9.0. I checked my pytorch is also 0.4.1.
> > > Thanks!
> > > @chunhez
> > > Thanks for your reply!
> > > I am using the GCC 5.4.0 and CUDA 9.0,too. but the neural_renderer also need G++ compiler (I'm sorry that I forgot to note that,haha!), the older version just like 5.3 seems not working correctly, so I change the G++ to 9.4.
> 
> @hxlCHD Thanks for your reply! So you mean you have to use different versions for GCC and G++? You have GCC 5.4 and G++9.4?

yes!

**Comment by chunhez** [comment]
> > > > > I have faced this same issue and solved it.But I don't konw whether this is right way.I just make it run.This is my way:
> > > > > 
> > > > > 1. change the CUDA version and GCC version, just like what you have did
> > > > > 2. clone the source file of neural renderer from github
> > > > > 3. check the pytorch version. For me is 0.4.1, But the readme recommend 0.4.0, I konw from a blog which said that higher version has some syntax changes, high version use TORCH_CHECK instead of AT_CHECK. so I just edit all the cpp files in this folder:/yourWorkSpace/neural_renderer/neural_renderer/cuda, replace all the TORCH_CHECK to AT_CHECK.
> > > > > 4. then compile the source code i have modified. `python setup.py install` I run this command in the msf-adv environment.
> > > > > 5. remove the neural-renderer-pytorch  which installed by conda. use this commend to uninstall `pip uninstall neural-renderer-pytorch=1.1.3`, I think you can edit the requirements.yml to avoid installing neural-renderer-pytorch from begin and then perform the previous step.
> > > > >    I hope these will help you！
> > > > 
> > > > 
> > > > @[hxlCHD](https://github.com/hxlCHD) Hi, I followed your instructions but when I tried to run command `python setup.py install`, it gave the error that 'TORCH_CHECK' was not declared in this scope. Could you specify what versions for GCC and CUDA you are using? I'm using GCC 5.4 and CUDA 9.0. I checked my pytorch is also 0.4.1.
> > > > Thanks!
> > > > @chunhez
> > > > Thanks for your reply!
> > > > I am using the GCC 5.4.0 and CUDA 9.0,too. but the neural_renderer also need G++ compiler (I'm sorry that I forgot to note that,haha!), the older version just like 5.3 seems not working correctly, so I change the G++ to 9.4.
> > 
> > 
> > @hxlCHD Thanks for your reply! So you mean you have to use different versions for GCC and G++? You have GCC 5.4 and G++9.4?
> 
> yes!

@hxlCHD I followed your steps and finally make it work. The difference is that I use pytorch 1.4.0, cuda 10.0 and gcc 5.4. Also, I do need to change all the AT_CHECK to TORCH_CHECK. Also thanks for your help!

**Comment by hxlCHD** [comment]
> > > > > > I have faced this same issue and solved it.But I don't konw whether this is right way.I just make it run.This is my way:
> > > > > > 
> > > > > > 1. change the CUDA version and GCC version, just like what you have did
> > > > > > 2. clone the source file of neural renderer from github
> > > > > > 3. check the pytorch version. For me is 0.4.1, But the readme recommend 0.4.0, I konw from a blog which said that higher version has some syntax changes, high version use TORCH_CHECK instead of AT_CHECK. so I just edit all the cpp files in this folder:/yourWorkSpace/neural_renderer/neural_renderer/cuda, replace all the TORCH_CHECK to AT_CHECK.
> > > > > > 4. then compile the source code i have modified. `python setup.py install` I run this command in the msf-adv environment.
> > > > > > 5. remove the neural-renderer-pytorch  which installed by conda. use this commend to uninstall `pip uninstall neural-renderer-pytorch=1.1.3`, I think you can edit the requirements.yml to avoid installing neural-renderer-pytorch from begin and then perform the previous step.
> > > > > >    I hope these will help you！
> > > > > 
> > > > > 
> > > > > @[hxlCHD](https://github.com/hxlCHD) Hi, I followed your instructions but when I tried to run command `python setup.py install`, it gave the error that 'TORCH_CHECK' was not declared in this scope. Could you specify what versions for GCC and CUDA you are using? I'm using GCC 5.4 and CUDA 9.0. I checked my pytorch is also 0.4.1.
> > > > > Thanks!
> > > > > @chunhez
> > > > > Thanks for your reply!
> > > > > I am using the GCC 5.4.0 and CUDA 9.0,too. but the neural_renderer also need G++ compiler (I'm sorry that I forgot to note that,haha!), the older version just like 5.3 seems not working correctly, so I change the G++ to 9.4.
> > > 
> > > 
> > > @hxlCHD Thanks for your reply! So you mean you have to use different versions for GCC and G++? You have GCC 5.4 and G++9.4?
> > 
> > 
> > yes!
> 
> @hxlCHD I followed your steps and finally make it work. The difference is that I use pytorch 1.4.0, cuda 10.0 and gcc 5.4. Also, I do need to change all the AT_CHECK to TORCH_CHECK. Also thanks for your help!

@chunhez It's my  pleasure！
